project:
  type: website
  output-dir: docs

website:
  title: "blog"
  search: true
  navbar:
    right:
      - about.qmd
      - text: "Workshops"
        href: https://karbartolome.github.io/workshops/
      - icon: github
        href: https://github.com/karbartolome
      - icon: twitter
        href: https://twitter.com/karbartolome
      - icon: linkedin
        href: https://www.linkedin.com/in/karinabartolome/
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: search-header.html



